name: el_manassa
description: "Stunning educational platform for Egypt"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.2.0
  
  # Navigation
  go_router: ^12.0.0
  
  # Animations
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  rive: ^0.12.0
  animated_text_kit: ^4.2.2
  
  # UI Components
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  glass_kit: ^3.0.0
  flutter_slidable: ^3.0.1
  smooth_page_indicator: ^1.1.0
  
  # Localization
  intl: ^0.20.2
  
  # Storage
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  
  # API
  dio: ^5.3.0
  retrofit: ^4.0.0
  json_annotation: ^4.8.1
  
  # Theme & Design
  dynamic_color: ^1.6.8
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  
  # Utilities
  connectivity_plus: ^5.0.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  
  # Media
  video_player: ^2.8.1
  chewie: ^1.7.4
  image_picker: ^1.0.4
  audioplayers: ^5.2.1
  
  # Forms & Validation
  reactive_forms: ^16.1.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.6
  
  # Icons
  cupertino_icons: ^1.0.6
  flutter_vector_icons: ^2.0.0
  
  # Utilities
  equatable: ^2.0.5
  uuid: ^4.2.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    # Arabic fonts
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    
    # English fonts
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0EA5E9"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#0EA5E9"
  image: assets/images/splash_logo.png
  android_12:
    color: "#0EA5E9"
    image: assets/images/splash_logo.png
